# banco_ingredientes.py
# Banco de dados nutricional de ingredientes naturais para suplementos caseiros
# Dados baseados em fontes: USDA FoodData Central, TACO (Tabela Brasileira)

INGREDIENTES = {
    "aveia_em_flocos": {
        "nome": "Aveia em Flocos",
        "emoji": "🌾",
        "categoria": "Carboidrato Complexo",
        "descricao": "Cereal integral rico em beta-glucana, fibras solúveis e energia sustentada de baixo índice glicêmico.",
        "onde_comprar": "Supermercado",
        "nutri": {
            "kcal": 389,
            "proteinas_g": 16.9,
            "carboidratos_g": 66.3,
            "fibras_g": 10.6,
            "gorduras_g": 6.9,
            "gorduras_sat_g": 1.2,
            "sodio_mg": 2,
            "potassio_mg": 429,
            "calcio_mg": 54,
            "ferro_mg": 4.7,
            "magnesio_mg": 177,
            "zinco_mg": 3.97,
        },
        "aa": {
            "Leucina*": 1.28, "Isoleucina*": 0.69, "Valina*": 0.94,
            "Lisina*": 0.70, "Metionina*": 0.31, "Fenilalanina*": 0.90,
            "Treonina*": 0.57, "Triptofano*": 0.23, "Histidina*": 0.41,
            "Arginina": 1.19, "Alanina": 0.88, "Ác. Aspártico": 1.45,
            "Cistina": 0.41, "Ác. Glutâmico": 3.71, "Glicina": 0.84,
            "Prolina": 0.93, "Serina": 0.76, "Tirosina": 0.57,
        },
        "objetivos": ["massa", "energia", "resistencia", "recuperacao"],
        "dose_ref_g": 50,
        "funcao": "Base energética de carboidratos complexos com fibra e beta-glucana",
    },

    "proteina_de_ervilha": {
        "nome": "Proteína de Ervilha",
        "emoji": "💚",
        "categoria": "Proteína Vegetal",
        "descricao": "Proteína isolada de ervilha amarela, vegana, com ótimo perfil de aminoácidos essenciais e boa digestibilidade.",
        "onde_comprar": "Loja de produtos naturais / Online",
        "nutri": {
            "kcal": 370, "proteinas_g": 80.0, "carboidratos_g": 7.0,
            "fibras_g": 2.0, "gorduras_g": 6.0, "gorduras_sat_g": 1.0,
            "sodio_mg": 400, "potassio_mg": 150, "calcio_mg": 100,
            "ferro_mg": 7.0, "magnesio_mg": 50, "zinco_mg": 2.5,
        },
        "aa": {
            "Leucina*": 6.78, "Isoleucina*": 3.56, "Valina*": 3.75,
            "Lisina*": 5.68, "Metionina*": 0.95, "Fenilalanina*": 4.12,
            "Treonina*": 2.90, "Triptofano*": 0.71, "Histidina*": 2.01,
            "Arginina": 6.55, "Alanina": 3.78, "Ác. Aspártico": 8.72,
            "Cistina": 0.82, "Ác. Glutâmico": 13.80, "Glicina": 3.41,
            "Prolina": 3.65, "Serina": 3.76, "Tirosina": 2.99,
        },
        "objetivos": ["massa", "gordura", "recuperacao"],
        "dose_ref_g": 30,
        "funcao": "Principal fonte proteica vegetal da receita",
    },

    "clara_de_ovo_em_po": {
        "nome": "Clara de Ovo em Pó",
        "emoji": "🥚",
        "categoria": "Proteína Animal",
        "descricao": "Albumina desidratada de alto valor biológico, rápida digestão e praticamente sem gordura.",
        "onde_comprar": "Loja de suplementos naturais / Online",
        "nutri": {
            "kcal": 381, "proteinas_g": 82.0, "carboidratos_g": 7.0,
            "fibras_g": 0.0, "gorduras_g": 0.5, "gorduras_sat_g": 0.0,
            "sodio_mg": 1165, "potassio_mg": 520, "calcio_mg": 81,
            "ferro_mg": 0.5, "magnesio_mg": 31, "zinco_mg": 0.2,
        },
        "aa": {
            "Leucina*": 8.29, "Isoleucina*": 6.52, "Valina*": 7.01,
            "Lisina*": 7.14, "Metionina*": 4.13, "Fenilalanina*": 5.94,
            "Treonina*": 4.79, "Triptofano*": 1.47, "Histidina*": 2.35,
            "Arginina": 5.69, "Alanina": 6.61, "Ác. Aspártico": 11.38,
            "Cistina": 2.55, "Ác. Glutâmico": 13.98, "Glicina": 3.69,
            "Prolina": 3.79, "Serina": 8.13, "Tirosina": 4.02,
        },
        "objetivos": ["massa", "recuperacao"],
        "dose_ref_g": 30,
        "funcao": "Proteína completa de alto valor biológico (albumina)",
    },

    "semente_de_canhamo": {
        "nome": "Semente de Cânhamo",
        "emoji": "🌿",
        "categoria": "Proteína + Ômega-3",
        "descricao": "Proteína completa com todos os aminoácidos essenciais, rica em ômega-3, ômega-6 e magnésio.",
        "onde_comprar": "Empório natural / Loja de produtos naturais",
        "nutri": {
            "kcal": 553, "proteinas_g": 31.6, "carboidratos_g": 8.7,
            "fibras_g": 4.0, "gorduras_g": 48.8, "gorduras_sat_g": 4.6,
            "sodio_mg": 5, "potassio_mg": 1200, "calcio_mg": 70,
            "ferro_mg": 7.95, "magnesio_mg": 700, "zinco_mg": 9.9,
        },
        "aa": {
            "Leucina*": 2.16, "Isoleucina*": 1.28, "Valina*": 1.93,
            "Lisina*": 1.27, "Metionina*": 0.93, "Fenilalanina*": 1.44,
            "Treonina*": 1.17, "Triptofano*": 0.37, "Histidina*": 0.91,
            "Arginina": 3.76, "Alanina": 1.67, "Ác. Aspártico": 3.22,
            "Cistina": 0.65, "Ác. Glutâmico": 5.51, "Glicina": 1.38,
            "Prolina": 1.37, "Serina": 1.55, "Tirosina": 1.11,
        },
        "objetivos": ["massa", "gordura", "recuperacao"],
        "dose_ref_g": 20,
        "funcao": "Proteína completa vegetal com ômega-3 anti-inflamatório",
    },

    "semente_de_chia": {
        "nome": "Semente de Chia",
        "emoji": "⚫",
        "categoria": "Ômega-3 / Fibra",
        "descricao": "Campeã em ômega-3 vegetal, cálcio e fibras. Forma gel que aumenta a saciedade.",
        "onde_comprar": "Supermercado",
        "nutri": {
            "kcal": 486, "proteinas_g": 16.5, "carboidratos_g": 42.1,
            "fibras_g": 34.4, "gorduras_g": 30.7, "gorduras_sat_g": 3.3,
            "sodio_mg": 16, "potassio_mg": 407, "calcio_mg": 631,
            "ferro_mg": 7.7, "magnesio_mg": 335, "zinco_mg": 4.58,
        },
        "aa": {
            "Leucina*": 1.37, "Isoleucina*": 0.80, "Valina*": 0.95,
            "Lisina*": 1.02, "Metionina*": 0.59, "Fenilalanina*": 1.02,
            "Treonina*": 0.64, "Triptofano*": 0.44, "Histidina*": 0.53,
            "Arginina": 2.14, "Alanina": 1.00, "Ác. Aspártico": 1.69,
            "Cistina": 0.38, "Ác. Glutâmico": 3.60, "Glicina": 0.92,
            "Prolina": 0.87, "Serina": 1.05, "Tirosina": 0.56,
        },
        "objetivos": ["gordura", "recuperacao", "resistencia"],
        "dose_ref_g": 15,
        "funcao": "Ômega-3 vegetal, fibra solúvel e saciedade",
    },

    "linhaca_dourada": {
        "nome": "Linhaça Dourada",
        "emoji": "🟡",
        "categoria": "Ômega-3 / Fibra",
        "descricao": "Rica em ALA (ômega-3), lignanas antioxidantes e fibras que regulam o trânsito intestinal.",
        "onde_comprar": "Supermercado",
        "nutri": {
            "kcal": 534, "proteinas_g": 18.3, "carboidratos_g": 28.9,
            "fibras_g": 27.3, "gorduras_g": 42.2, "gorduras_sat_g": 3.7,
            "sodio_mg": 30, "potassio_mg": 813, "calcio_mg": 255,
            "ferro_mg": 5.7, "magnesio_mg": 392, "zinco_mg": 4.34,
        },
        "aa": {
            "Leucina*": 1.24, "Isoleucina*": 0.90, "Valina*": 1.01,
            "Lisina*": 0.86, "Metionina*": 0.37, "Fenilalanina*": 1.00,
            "Treonina*": 0.73, "Triptofano*": 0.30, "Histidina*": 0.49,
            "Arginina": 2.48, "Alanina": 1.09, "Ác. Aspártico": 2.15,
            "Cistina": 0.39, "Ác. Glutâmico": 4.13, "Glicina": 1.17,
            "Prolina": 0.84, "Serina": 0.95, "Tirosina": 0.64,
        },
        "objetivos": ["massa", "gordura", "resistencia", "recuperacao", "energia"],
        "dose_ref_g": 15,
        "funcao": "Ômega-3 anti-inflamatório e fibra prebiótica",
    },

    "espirulina": {
        "nome": "Espirulina",
        "emoji": "🌊",
        "categoria": "Superalimento Proteico",
        "descricao": "Alga de altíssima densidade nutricional: 57g de proteína/100g, ferro biodisponível, B12 vegetal e antioxidantes.",
        "onde_comprar": "Loja de produtos naturais / Farmácia de manipulação",
        "nutri": {
            "kcal": 290, "proteinas_g": 57.5, "carboidratos_g": 23.9,
            "fibras_g": 3.6, "gorduras_g": 7.7, "gorduras_sat_g": 2.7,
            "sodio_mg": 1048, "potassio_mg": 1363, "calcio_mg": 120,
            "ferro_mg": 28.5, "magnesio_mg": 195, "zinco_mg": 2.0,
        },
        "aa": {
            "Leucina*": 4.95, "Isoleucina*": 3.26, "Valina*": 3.51,
            "Lisina*": 3.03, "Metionina*": 1.15, "Fenilalanina*": 2.78,
            "Treonina*": 2.97, "Triptofano*": 0.93, "Histidina*": 1.09,
            "Arginina": 4.15, "Alanina": 4.51, "Ác. Aspártico": 5.95,
            "Cistina": 0.66, "Ác. Glutâmico": 8.38, "Glicina": 2.97,
            "Prolina": 2.38, "Serina": 2.99, "Tirosina": 2.58,
        },
        "objetivos": ["massa", "gordura", "resistencia", "recuperacao"],
        "dose_ref_g": 10,
        "funcao": "Superalimento: ferro, B12 vegetal e proteína completa",
    },

    "cacau_em_po": {
        "nome": "Cacau em Pó 100% Puro",
        "emoji": "🍫",
        "categoria": "Antioxidante",
        "descricao": "Fonte poderosa de magnésio, flavonoides antioxidantes e teobromina que melhora humor e foco.",
        "onde_comprar": "Supermercado / Empório natural",
        "nutri": {
            "kcal": 228, "proteinas_g": 19.6, "carboidratos_g": 57.9,
            "fibras_g": 33.2, "gorduras_g": 13.7, "gorduras_sat_g": 8.1,
            "sodio_mg": 21, "potassio_mg": 1524, "calcio_mg": 128,
            "ferro_mg": 13.9, "magnesio_mg": 499, "zinco_mg": 6.81,
        },
        "aa": {
            "Leucina*": 1.37, "Isoleucina*": 0.68, "Valina*": 1.09,
            "Lisina*": 1.09, "Metionina*": 0.27, "Fenilalanina*": 1.08,
            "Treonina*": 0.67, "Triptofano*": 0.29, "Histidina*": 0.47,
            "Arginina": 2.26, "Alanina": 1.01, "Ác. Aspártico": 2.03,
            "Cistina": 0.21, "Ác. Glutâmico": 4.38, "Glicina": 0.95,
            "Prolina": 0.90, "Serina": 0.99, "Tirosina": 0.66,
        },
        "objetivos": ["massa", "gordura", "energia", "recuperacao"],
        "dose_ref_g": 15,
        "funcao": "Magnésio, antioxidantes, sabor e humor",
    },

    "amendoim_em_po": {
        "nome": "Amendoim em Pó Desnatado",
        "emoji": "🥜",
        "categoria": "Proteína Vegetal",
        "descricao": "Alto teor proteico com gordura reduzida, rico em niacina (B3), resveratrol e arginina.",
        "onde_comprar": "Supermercado / Empório natural",
        "nutri": {
            "kcal": 350, "proteinas_g": 45.0, "carboidratos_g": 25.0,
            "fibras_g": 8.0, "gorduras_g": 10.0, "gorduras_sat_g": 1.5,
            "sodio_mg": 70, "potassio_mg": 750, "calcio_mg": 92,
            "ferro_mg": 4.6, "magnesio_mg": 168, "zinco_mg": 3.3,
        },
        "aa": {
            "Leucina*": 2.76, "Isoleucina*": 1.56, "Valina*": 1.81,
            "Lisina*": 1.42, "Metionina*": 0.54, "Fenilalanina*": 2.01,
            "Treonina*": 1.09, "Triptofano*": 0.48, "Histidina*": 0.95,
            "Arginina": 2.90, "Alanina": 1.77, "Ác. Aspártico": 5.47,
            "Cistina": 0.57, "Ác. Glutâmico": 7.57, "Glicina": 2.36,
            "Prolina": 1.71, "Serina": 1.98, "Tirosina": 1.60,
        },
        "objetivos": ["massa", "energia"],
        "dose_ref_g": 20,
        "funcao": "Proteína vegetal e arginina para fluxo sanguíneo",
    },

    "farinha_de_banana_verde": {
        "nome": "Farinha de Banana Verde",
        "emoji": "🍌",
        "categoria": "Carboidrato Funcional",
        "descricao": "Amido resistente prebiótico que nutre a microbiota intestinal e fornece energia de baixo índice glicêmico.",
        "onde_comprar": "Empório natural / Supermercado",
        "nutri": {
            "kcal": 320, "proteinas_g": 3.9, "carboidratos_g": 78.4,
            "fibras_g": 15.0, "gorduras_g": 0.7, "gorduras_sat_g": 0.3,
            "sodio_mg": 11, "potassio_mg": 742, "calcio_mg": 30,
            "ferro_mg": 2.7, "magnesio_mg": 76, "zinco_mg": 0.7,
        },
        "aa": {
            "Leucina*": 0.28, "Isoleucina*": 0.16, "Valina*": 0.19,
            "Lisina*": 0.20, "Metionina*": 0.06, "Fenilalanina*": 0.18,
            "Treonina*": 0.15, "Triptofano*": 0.05, "Histidina*": 0.09,
            "Arginina": 0.20, "Alanina": 0.22, "Ác. Aspártico": 0.38,
            "Cistina": 0.06, "Ác. Glutâmico": 0.76, "Glicina": 0.18,
            "Prolina": 0.20, "Serina": 0.19, "Tirosina": 0.10,
        },
        "objetivos": ["energia", "resistencia", "massa"],
        "dose_ref_g": 30,
        "funcao": "Amido resistente de baixo IG e potássio",
    },

    "tamara_em_po": {
        "nome": "Tâmara em Pó",
        "emoji": "🌴",
        "categoria": "Carboidrato Natural / Adoçante",
        "descricao": "Açúcar natural com minerais, fibras e índice glicêmico moderado. Adoçante e energia para o treino.",
        "onde_comprar": "Empório natural / Online",
        "nutri": {
            "kcal": 277, "proteinas_g": 1.8, "carboidratos_g": 74.0,
            "fibras_g": 6.7, "gorduras_g": 0.2, "gorduras_sat_g": 0.0,
            "sodio_mg": 1, "potassio_mg": 696, "calcio_mg": 64,
            "ferro_mg": 0.9, "magnesio_mg": 54, "zinco_mg": 0.44,
        },
        "aa": {
            "Leucina*": 0.11, "Isoleucina*": 0.07, "Valina*": 0.10,
            "Lisina*": 0.09, "Metionina*": 0.02, "Fenilalanina*": 0.08,
            "Treonina*": 0.06, "Triptofano*": 0.01, "Histidina*": 0.04,
            "Arginina": 0.09, "Alanina": 0.12, "Ác. Aspártico": 0.22,
            "Cistina": 0.04, "Ác. Glutâmico": 0.36, "Glicina": 0.08,
            "Prolina": 0.12, "Serina": 0.10, "Tirosina": 0.06,
        },
        "objetivos": ["energia", "resistencia"],
        "dose_ref_g": 20,
        "funcao": "Adoçante natural e energia de fácil digestão",
    },

    "levedo_de_cerveja": {
        "nome": "Levedo de Cerveja / Levedura Nutricional",
        "emoji": "🟤",
        "categoria": "Vitaminas B / Proteína",
        "descricao": "Rico em todo o complexo B (incluindo B12), aminoácidos essenciais e glutamina. Sabor levemente queijoso.",
        "onde_comprar": "Farmácia / Loja de produtos naturais",
        "nutri": {
            "kcal": 325, "proteinas_g": 52.0, "carboidratos_g": 38.0,
            "fibras_g": 26.0, "gorduras_g": 2.0, "gorduras_sat_g": 0.5,
            "sodio_mg": 100, "potassio_mg": 2000, "calcio_mg": 60,
            "ferro_mg": 18.0, "magnesio_mg": 230, "zinco_mg": 7.9,
        },
        "aa": {
            "Leucina*": 3.38, "Isoleucina*": 2.22, "Valina*": 2.89,
            "Lisina*": 3.56, "Metionina*": 0.78, "Fenilalanina*": 2.10,
            "Treonina*": 2.38, "Triptofano*": 0.64, "Histidina*": 1.20,
            "Arginina": 2.68, "Alanina": 3.03, "Ác. Aspártico": 5.10,
            "Cistina": 0.59, "Ác. Glutâmico": 8.93, "Glicina": 2.20,
            "Prolina": 2.05, "Serina": 2.39, "Tirosina": 1.75,
        },
        "objetivos": ["massa", "energia", "recuperacao"],
        "dose_ref_g": 10,
        "funcao": "Complexo B, zinco, ferro e aminoácidos",
    },

    "beterraba_em_po": {
        "nome": "Beterraba em Pó",
        "emoji": "🟣",
        "categoria": "Pré-treino Natural / Nitrato",
        "descricao": "Concentrado de nitratos que aumentam a vasodilatação, melhoram o fluxo de oxigênio e a resistência aeróbica.",
        "onde_comprar": "Loja de produtos naturais / Online",
        "nutri": {
            "kcal": 300, "proteinas_g": 9.9, "carboidratos_g": 68.0,
            "fibras_g": 13.0, "gorduras_g": 1.0, "gorduras_sat_g": 0.2,
            "sodio_mg": 350, "potassio_mg": 3500, "calcio_mg": 170,
            "ferro_mg": 9.0, "magnesio_mg": 120, "zinco_mg": 2.0,
        },
        "aa": {
            "Leucina*": 0.59, "Isoleucina*": 0.41, "Valina*": 0.54,
            "Lisina*": 0.58, "Metionina*": 0.12, "Fenilalanina*": 0.44,
            "Treonina*": 0.40, "Triptofano*": 0.13, "Histidina*": 0.21,
            "Arginina": 0.49, "Alanina": 0.44, "Ác. Aspártico": 1.03,
            "Cistina": 0.11, "Ác. Glutâmico": 1.96, "Glicina": 0.44,
            "Prolina": 0.39, "Serina": 0.43, "Tirosina": 0.32,
        },
        "objetivos": ["resistencia", "energia"],
        "dose_ref_g": 10,
        "funcao": "Nitratos naturais para vasodilatação e endurance",
    },

    "maca_peruana": {
        "nome": "Maca Peruana em Pó",
        "emoji": "🌺",
        "categoria": "Adaptógeno",
        "descricao": "Raiz andina adaptógena que melhora energia, libido, equilíbrio hormonal e resistência ao estresse físico.",
        "onde_comprar": "Loja de produtos naturais / Online",
        "nutri": {
            "kcal": 325, "proteinas_g": 14.0, "carboidratos_g": 71.4,
            "fibras_g": 8.5, "gorduras_g": 2.2, "gorduras_sat_g": 0.5,
            "sodio_mg": 18, "potassio_mg": 2050, "calcio_mg": 250,
            "ferro_mg": 14.7, "magnesio_mg": 114, "zinco_mg": 3.8,
        },
        "aa": {
            "Leucina*": 0.91, "Isoleucina*": 0.47, "Valina*": 0.79,
            "Lisina*": 0.99, "Metionina*": 0.28, "Fenilalanina*": 0.55,
            "Treonina*": 0.33, "Triptofano*": 0.10, "Histidina*": 0.22,
            "Arginina": 0.97, "Alanina": 0.63, "Ác. Aspártico": 1.38,
            "Cistina": 0.12, "Ác. Glutâmico": 1.58, "Glicina": 0.68,
            "Prolina": 0.50, "Serina": 0.50, "Tirosina": 0.30,
        },
        "objetivos": ["energia", "gordura", "resistencia"],
        "dose_ref_g": 5,
        "funcao": "Adaptógeno para energia, hormônios e libido",
    },

    "guarana_em_po": {
        "nome": "Guaraná em Pó",
        "emoji": "🔴",
        "categoria": "Estimulante Natural",
        "descricao": "Fruto amazônico com ~4% de cafeína natural (4x mais que café), teobromina e teofilina para foco e energia.",
        "onde_comprar": "Supermercado / Farmácia",
        "nutri": {
            "kcal": 302, "proteinas_g": 9.7, "carboidratos_g": 62.0,
            "fibras_g": 5.0, "gorduras_g": 3.0, "gorduras_sat_g": 1.0,
            "sodio_mg": 0, "potassio_mg": 0, "calcio_mg": 10,
            "ferro_mg": 2.0, "magnesio_mg": 40, "zinco_mg": 0.5,
        },
        "aa": {
            "Leucina*": 0.60, "Isoleucina*": 0.40, "Valina*": 0.50,
            "Lisina*": 0.50, "Metionina*": 0.10, "Fenilalanina*": 0.45,
            "Treonina*": 0.35, "Triptofano*": 0.10, "Histidina*": 0.18,
            "Arginina": 0.55, "Alanina": 0.45, "Ác. Aspártico": 0.90,
            "Cistina": 0.10, "Ác. Glutâmico": 1.50, "Glicina": 0.45,
            "Prolina": 0.42, "Serina": 0.40, "Tirosina": 0.30,
        },
        "objetivos": ["energia", "resistencia"],
        "dose_ref_g": 3,
        "funcao": "Cafeína natural, foco e desempenho (≈120mg cafeína/3g)",
    },

    "curcuma": {
        "nome": "Cúrcuma em Pó",
        "emoji": "🟠",
        "categoria": "Anti-inflamatório",
        "descricao": "Raiz anti-inflamatória potente com curcumina. Reduz dor muscular, inflamação e acelera a recuperação.",
        "onde_comprar": "Supermercado",
        "nutri": {
            "kcal": 354, "proteinas_g": 7.8, "carboidratos_g": 64.9,
            "fibras_g": 21.1, "gorduras_g": 9.9, "gorduras_sat_g": 3.1,
            "sodio_mg": 38, "potassio_mg": 2525, "calcio_mg": 183,
            "ferro_mg": 41.4, "magnesio_mg": 193, "zinco_mg": 4.35,
        },
        "aa": {
            "Leucina*": 0.53, "Isoleucina*": 0.35, "Valina*": 0.45,
            "Lisina*": 0.32, "Metionina*": 0.10, "Fenilalanina*": 0.45,
            "Treonina*": 0.29, "Triptofano*": 0.09, "Histidina*": 0.15,
            "Arginina": 0.52, "Alanina": 0.38, "Ác. Aspártico": 0.69,
            "Cistina": 0.07, "Ác. Glutâmico": 1.35, "Glicina": 0.42,
            "Prolina": 0.37, "Serina": 0.40, "Tirosina": 0.28,
        },
        "objetivos": ["recuperacao"],
        "dose_ref_g": 3,
        "funcao": "Anti-inflamatório potente para recuperação muscular",
    },

    "gengibre_em_po": {
        "nome": "Gengibre em Pó",
        "emoji": "🫚",
        "categoria": "Anti-inflamatório / Digestivo",
        "descricao": "Termogênico natural com gingeróis, melhora a digestão proteica, reduz náusea e inflamação.",
        "onde_comprar": "Supermercado",
        "nutri": {
            "kcal": 335, "proteinas_g": 8.9, "carboidratos_g": 71.6,
            "fibras_g": 14.1, "gorduras_g": 4.2, "gorduras_sat_g": 1.1,
            "sodio_mg": 27, "potassio_mg": 1320, "calcio_mg": 116,
            "ferro_mg": 19.8, "magnesio_mg": 214, "zinco_mg": 3.64,
        },
        "aa": {
            "Leucina*": 0.53, "Isoleucina*": 0.38, "Valina*": 0.43,
            "Lisina*": 0.38, "Metionina*": 0.12, "Fenilalanina*": 0.38,
            "Treonina*": 0.29, "Triptofano*": 0.09, "Histidina*": 0.17,
            "Arginina": 0.69, "Alanina": 0.40, "Ác. Aspártico": 0.79,
            "Cistina": 0.05, "Ác. Glutâmico": 1.23, "Glicina": 0.38,
            "Prolina": 0.30, "Serina": 0.31, "Tirosina": 0.22,
        },
        "objetivos": ["recuperacao", "gordura"],
        "dose_ref_g": 3,
        "funcao": "Digestão e anti-inflamatório termogênico",
    },

    "canela_em_po": {
        "nome": "Canela em Pó",
        "emoji": "🍂",
        "categoria": "Regulador Glicêmico",
        "descricao": "Melhora a sensibilidade à insulina, regula a glicose sanguínea e potencializa a queima de gordura.",
        "onde_comprar": "Supermercado",
        "nutri": {
            "kcal": 247, "proteinas_g": 4.0, "carboidratos_g": 80.6,
            "fibras_g": 53.1, "gorduras_g": 1.2, "gorduras_sat_g": 0.3,
            "sodio_mg": 10, "potassio_mg": 431, "calcio_mg": 1002,
            "ferro_mg": 8.3, "magnesio_mg": 60, "zinco_mg": 1.83,
        },
        "aa": {
            "Leucina*": 0.25, "Isoleucina*": 0.17, "Valina*": 0.21,
            "Lisina*": 0.18, "Metionina*": 0.04, "Fenilalanina*": 0.18,
            "Treonina*": 0.14, "Triptofano*": 0.04, "Histidina*": 0.08,
            "Arginina": 0.27, "Alanina": 0.19, "Ác. Aspártico": 0.39,
            "Cistina": 0.05, "Ác. Glutâmico": 0.72, "Glicina": 0.24,
            "Prolina": 0.19, "Serina": 0.18, "Tirosina": 0.14,
        },
        "objetivos": ["gordura", "energia"],
        "dose_ref_g": 3,
        "funcao": "Sensibilidade à insulina e controle glicêmico",
    },

    "farinha_de_quinoa": {
        "nome": "Farinha de Quinoa",
        "emoji": "⭐",
        "categoria": "Proteína Completa / Carboidrato",
        "descricao": "Único grão vegetal com proteína completa (todos os aminoácidos essenciais). Alto em ferro e magnésio.",
        "onde_comprar": "Empório natural / Supermercado",
        "nutri": {
            "kcal": 368, "proteinas_g": 14.1, "carboidratos_g": 64.2,
            "fibras_g": 7.0, "gorduras_g": 6.1, "gorduras_sat_g": 0.7,
            "sodio_mg": 5, "potassio_mg": 563, "calcio_mg": 47,
            "ferro_mg": 4.6, "magnesio_mg": 197, "zinco_mg": 3.1,
        },
        "aa": {
            "Leucina*": 0.84, "Isoleucina*": 0.50, "Valina*": 0.59,
            "Lisina*": 0.77, "Metionina*": 0.31, "Fenilalanina*": 0.59,
            "Treonina*": 0.42, "Triptofano*": 0.17, "Histidina*": 0.41,
            "Arginina": 1.09, "Alanina": 0.59, "Ác. Aspártico": 1.09,
            "Cistina": 0.20, "Ác. Glutâmico": 1.65, "Glicina": 0.69,
            "Prolina": 0.71, "Serina": 0.57, "Tirosina": 0.27,
        },
        "objetivos": ["massa", "energia", "resistencia"],
        "dose_ref_g": 30,
        "funcao": "Proteína completa vegetal e carboidrato de qualidade",
    },
}

# Objetivos disponíveis com suas configurações
OBJETIVOS = {
    "massa": {
        "nome": "Ganho de Massa Muscular",
        "emoji": "💪",
        "cor": "#e74c3c",
        "descricao": "Maximize a síntese proteica, recuperação e energia para treinos de força.",
        "macro_alvo": {
            "proteinas_g": (25, 35),
            "carboidratos_g": (40, 60),
            "gorduras_g": (8, 14),
            "kcal": (380, 480),
        },
        "ingredientes_prioritarios": [
            "clara_de_ovo_em_po", "proteina_de_ervilha",
            "aveia_em_flocos", "farinha_de_banana_verde",
            "semente_de_canhamo", "linhaca_dourada",
            "cacau_em_po", "levedo_de_cerveja",
        ],
        "dica": "Consuma 30–60 minutos após o treino para maximizar a síntese proteica.",
    },
    "gordura": {
        "nome": "Queima de Gordura",
        "emoji": "🔥",
        "cor": "#f39c12",
        "descricao": "Alta proteína, baixo carboidrato, termogênicos e saciedade prolongada.",
        "macro_alvo": {
            "proteinas_g": (25, 35),
            "carboidratos_g": (5, 15),
            "gorduras_g": (8, 14),
            "kcal": (230, 320),
        },
        "ingredientes_prioritarios": [
            "proteina_de_ervilha", "semente_de_canhamo",
            "semente_de_chia", "espirulina",
            "cacau_em_po", "canela_em_po",
            "gengibre_em_po", "maca_peruana",
        ],
        "dica": "Tome 30 minutos antes do treino ou no café da manhã para aumentar o metabolismo.",
    },
    "resistencia": {
        "nome": "Resistência e Endurance",
        "emoji": "🏃",
        "cor": "#27ae60",
        "descricao": "Carboidratos de qualidade, eletrólitos e nitratos para melhorar sua capacidade aeróbica.",
        "macro_alvo": {
            "proteinas_g": (10, 18),
            "carboidratos_g": (50, 70),
            "gorduras_g": (5, 10),
            "kcal": (300, 400),
        },
        "ingredientes_prioritarios": [
            "beterraba_em_po", "farinha_de_banana_verde",
            "aveia_em_flocos", "tamara_em_po",
            "espirulina", "linhaca_dourada",
            "farinha_de_quinoa",
        ],
        "dica": "Consuma 45–60 minutos antes do treino aeróbico ou prova.",
    },
    "recuperacao": {
        "nome": "Recuperação Muscular",
        "emoji": "🔄",
        "cor": "#8e44ad",
        "descricao": "Proteínas de rápida absorção, aminoácidos anti-catabólicos e anti-inflamatórios naturais.",
        "macro_alvo": {
            "proteinas_g": (25, 32),
            "carboidratos_g": (20, 35),
            "gorduras_g": (5, 10),
            "kcal": (250, 350),
        },
        "ingredientes_prioritarios": [
            "clara_de_ovo_em_po", "semente_de_canhamo",
            "tamara_em_po", "cacau_em_po",
            "curcuma", "gengibre_em_po",
            "linhaca_dourada", "espirulina",
        ],
        "dica": "Tome imediatamente após o treino (janela anabólica de 30–45 minutos).",
    },
    "energia": {
        "nome": "Energia e Performance",
        "emoji": "⚡",
        "cor": "#2980b9",
        "descricao": "Pré-treino natural com carboidratos de rápida disponibilidade, cafeína natural e vitaminas B.",
        "macro_alvo": {
            "proteinas_g": (8, 15),
            "carboidratos_g": (50, 70),
            "gorduras_g": (5, 10),
            "kcal": (280, 380),
        },
        "ingredientes_prioritarios": [
            "farinha_de_banana_verde", "tamara_em_po",
            "amendoim_em_po", "guarana_em_po",
            "levedo_de_cerveja", "cacau_em_po",
            "canela_em_po", "maca_peruana",
        ],
        "dica": "Tome 20–30 minutos antes do treino para máxima performance.",
    },
}
